# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Namhyeon Lee
title: Full-Stack Developer
email: namhyeon128@gmail.com
# email_title: Email (Email title override)
phone: +821034634569
# phone_title: Phone (Phone title override)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: namhyeonlee
linkedin_username: www.linkedin.com/in/namhyeon-lee-94194a268

# Additional icon links
# additional_links:
#   - title: Link name
#     icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#     url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/me.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello! I have developed a strong proficiency in <mark>JavaScript</mark>, <mark>HTML</mark>, <mark>CSS</mark>, and various frontend frameworks such as <mark>React</mark> and <mark>Next.js</mark> With three years of experience in the industry.
  Additionally, I possess experience in backend development using <mark>Node.js</mark>, <mark>Java</mark>, and <mark>MySQL</mark>, allowing me to develop full-stack applications and have a comprehensive understanding of how frontend and backend components work together.
  I have experience in agile development methodologies and version control systems such as Git as well.

  Skills and Tools
    - React
    - Next.js
    - React Native
    - AngularJs
    - Node.js
    - Java
    - MySQL
    - Git

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       border:
  #         weak # Value of `weak` will display a weak border below this item. # Any
  #         # other value (or no value) means no border will be displayed
  #       title: Project name
  #       link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #       link_text: Link Text
  #       additional_links:
  #         - title: Github page for project (eg. sproogen/modern-resume-theme)
  #           icon: fab fa-github
  #           url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #         - title: Github page for project (eg. sproogen/modern-resume-theme)
  #           icon: fab fa-github
  #           url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #       quote: >
  #         Short overview of the project (optional)
  #       description: | # this will include new lines to allow paragraphs
  #         Description about the work on/with the project
  - title: Experience
    layout: list
    content:
      - layout: right
        title: HectonProject
        sub_title: Full-Stack Developer
        caption: 06/2022 to Present
        link: https://www.hectonproject.com/
        quote: >
          HectonProject is a healthcare company that provides Silver Care services, which include nursing home counseling service platforms and solution product for nursing homes management and hosipital.
        description: | # this will include new lines to allow paragraphs
          - project1 <br>
          ■ Project Name: solution product for nursing homes<br>
          ■ Workers: Project Manager(1), Service Prject Manager(1), F/E(3), B/E(3), UI Developer(1) Designer(1)<br>
          ■ Position: full-stack developer(F/E - 70%, B/E - 30%)<br>
          ■ Contributions: 35%<br>
          ■ Env : AWS, GitLab, Jenkins, Sonarqube<br>
          ■ Tool : Eclipse, Visual Studio Code, MySQL Workbench<br>
          ■ Skill : Java, Spring framework, Nextjs, Typescript, SCSS, MySQL <br>
          ■ Description<br>
          ○ Full-stack engineer on the team responsible for developing a solution product for nursing home management. Mainly focused on developing thefront-end using Next.js and Typescript. Also contributed to developing APIs using Java and MySQL.<br>
          ○ Performed static code analysis using Sonarqube to ensure clean and high- quality code standards.<br>
          ○ Collaborated with cross-functional teams, and implementing cutting-edge technologies to enhance user experience.<br>
          ○ Initially developed and led the conversion of paper documents using the Oz Report solution, which is a reporting tool. Converting paper documents is a main function of the solution.<br>

          - project2 <br>
          ■ Project Name: nursing home counseling service platform’s back-office system<br>
          ■ Workers: Project Manager(1), Service Prject Manager(1), Full-Stack(3), UI Developer(1) Designer(1)<br>
          ■ Position: full-stack developer(F/E - 70%, B/E - 30%)<br>
          ■ Contributions: 35%<br>
          ■ Env : AWS, GitLab, Jenkins<br>
          ■ Tool : Eclipse, MySQL Workbench<br>
          ■ Skill : Java, Spring framework, Javascript, Angaular.js<br>
          ■ Description<br>
          ○ Full-stack engineer on the team responsible for developing the back-office system for the platform service. Primarily using Angular.js, Java, and MySQL.<br>
          ○ Developed common front-end components and functions, as well as built a file upload system on the back-end.<br>
          ○ Provided coaching to junior developers who joined the project.<br>
      - layout: right
        title: SoriZava(Freelancer Project)
        sub_title: Front-end Developer
        caption: 04/2022 to 05/2022
        link: https://baronote.com/account/info
        quote: >
          Sorizava provide the voice record note service.
        description: | # this will include new lines to allow paragraphs
          - project3 <br>
          ■ Project Name: voice record note service's homepage and back-office system<br>
          ■ Workers: Project Manager(1), F/E(1), B/E(2)<br>
          ■ Position: Front-end developer<br>
          ■ Contributions: F/E 100%<br>
          ■ Env : AWS, GitHub<br>
          ■ Tool : Visual Studio Code, Pigma<br>
          ■ Skill : React, Material-UI<br>
          ■ Description<br>
          ○ Responsible for developing the company's own service homepage and back-office system, primarily using React. Contributed 100% to front-end development.<br>
          ○ Collaborated with cross-functional teams using the Pigma tool.<br>
      - layout: right
        title: Doctorringo
        sub_title: Front-end Developer
        caption: 01/2022 to 04/2022
        link: https://baronote.com/account/info
        quote: >
          Doctoringo provides Social Network Services app that shares a portfolio for artists.
        description: | # this will include new lines to allow paragraphs
          - project4 <br>
          ■ Project Name: Tag&Tager Hybrid App<br>
          ■ Workers: Project Manager(1), F/E(1), B/E(2), Designer(1)<br>
          ■ Position: Front-end developer<br>
          ■ Contributions: F/E 100%<br>
          ■ Env : AWS, GitHub<br>
          ■ Tool : Visual Studio Code, Pigma, Xcode<br>
          ■ Skill : React Natvie, TypeScript, Redux-Toolkit, Styled-Components<br>
          ■ Description<br>
          ○ Developed the UI of the application.<br>
          ○ Focused on development to enhance the customer experience of the app.<br>
          ○ Managed the distribution of the app to both iOS and Android platforms, ensuring compatibility and optimal user experience.<br>

          - project5 <br>
          ■ Project Name: Tag&Tager Hybrid App service’s back-office system<br>
          ■ Workers: Project Manager(1), F/E(1), B/E(2)<br>
          ■ Position: Front-end developer<br>
          ■ Contributions: F/E 100%<br>
          ■ Env : AWS, GitHub<br>
          ■ Tool : Visual Studio Code, Pigma<br>
          ■ Skill : React, TypeScript, Redux-Toolkit, Material-UI<br>
          ■ Description<br>
          ○ Developed UI design of the application.<br>
          ○ Played a key role in the front-end development of the back-office system, including the initial development of common components and functions to improve efficiency and consistency.<br>
      - layout: right
        title: Awsome
        sub_title: Full-stack Developer
        caption: 01/2022 to 04/2022
        link: https://baronote.com/account/info
        quote: >
          At Awsome, a web application agency specializing in developing startup business platform.
        description: | # this will include new lines to allow paragraphs
          - project6 <br>
          ■ Project Name: Business Platform Construction for AI Solution Company<br>
          ■ Workers:Project Manager(1), Full-Stack(1)<br>
          ■ Position: Full-stack developer<br>
          ■ Contributions: F/E 50%, B/E 50%<br>
          ■ Env : AWS, GitHub<br>
          ■ Tool : Visual Studio Code, Pigma, Xcode<br>
          ■ Skill : React, React Native, Nodejs, MySQL, Firebase<br>
          ■ Description<br>
          ○ Developed front-end components using React.js, including membership registration, data transfer to the AI solution company's database, graph creation using result data, and the 'My Page' feature. Also developed the back-office system for this platform.<br>
          ○ Created a hybrid app using a web view library and implemented push notification services through Firebase.<br>
          ○ Developed APIs using Node.js and MySQL for seamless communication between the front-end and back-end of the application.<br>

          - project7 <br>
          ■ Project Name: Development of Web App for Daejeon City Epidemiological Investigation Report<br>
          ■ Workers: Project Manager(1), Full-Stack(1)<br>
          ■ Position:Full-stack developer<br>
          ■ Contributions: F/E 100%, B/E 100%<br>
          ■ Env : AWS, GitHub<br>
          ■ Tool : Visual Studio Code, Xcode<br>
          ■ Skill : React, React Native, Nodejs, MySQL<br>
          ■ Description<br>
          ○ Developed a report system application and back-office system using React.js.<br>
          ○ Created a hybrid app using a web view library and implemented push notification services through Firebase.<br>
          ○ Developed APIs using Node.js and constructed the database.<br>

          - project8 <br>
          ■ Project Name: Development of Android App for Seoul National University Foreign Students Guide<br>
          ■ Workers: Project Manager(1), F/E(1)<br>
          ■ Position: App developer<br>
          ■ Contributions: 100%<br>
          ■ Tool :  Visual Studio Code<br>
          ■ Skill : React Native<br>
          ■ Description<br>
          ○ Developed the UI of the application.<br>
          ○ Developed the map marker function and integrated it into the Android app.<br>
  - title: Education
    layout: list
    content:
      - layout: top-left
        title: TIS
        sub_title: Software Engineering Bootcamp
        caption: 09/2020 to 04/2021
        quote: >
        description: | # this will include new lines to allow paragraphs
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

      Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "node_modules",
    "vendor/bundle/",
    "vendor/cache/",
    "vendor/gems/",
    "vendor/ruby/",
    "lib/",
    "scripts/",
    "docker-compose.yml",
  ]
